name: storeSales
channels:
  - defaults
dependencies:
  - matplotlib
  - python
  - tensorflow
  - pandas
  - numpy
  - scipy
  - plotly
  - jupyter
  - scikit-learn
  - lightgbm
  - xgboost
  - statsmodels
  - seaborn


